# Generated by Django 4.2 on 2025-06-19 08:22

import django_choices_field.fields
import wasmer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wasmer_app",
            "0003_alter_deployedapp_id_alter_user_id_alter_user_plan_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="sent_at",
        ),
        migrations.AddField(
            model_name="email",
            name="receiver",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="external_id",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SENT", "SENT"),
                    ("FAILED", "FAILED"),
                    ("READ", "READ"),
                ],
                choices_enum=wasmer_app.models.EmailStatus,
                default="PENDING",
                max_length=7,
            ),
        ),
    ]
